name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - flask
  - flask-socketio
  - flask-cors
  - opencv
  - ultralytics
  - gunicorn
  - pytorch=2.3.0
  - torchvision=0.18.1
